---
- name: Uninstall stuff we don't actually need
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - phpunit

- name: Install necessary packages for proper system state
  apt: name={{ item }} state=latest
  with_items:
    - git
    - subversion

- name: Install Composer into the current directory
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer
  tags: [ 'common', 'composer' ]

- name: Rename Composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  tags: [ 'common', 'composer' ]

- name: Ensure Composer is executable
  file: path=/usr/local/bin/composer mode=a+x state=file
  tags: [ 'common', 'composer' ]

- name: Install PHPUnit into the current directory
  get_url: url=https://phar.phpunit.de/phpunit.phar dest=/tmp/phpunit.phar
  tags: [ 'common', 'phpunit' ]

- name: Rename PHPUnit
  shell: mv /tmp/phpunit.phar /usr/local/bin/phpunit creates=/usr/local/bin/phpunit
  tags: [ 'common', 'phpunit' ]

- name: Ensure PHPUnit is executable
  file: path=/usr/local/bin/phpunit mode=a+x state=file
  tags: [ 'common', 'phpunit' ]

- name: Install phpDocumentor into the current directory
  get_url: url=http://phpdoc.org/phpDocumentor.phar dest=/tmp/phpDocumentor.phar
  tags: [ 'common', 'phpdoc' ]

- name: Rename phpDocumentor
  shell: mv /tmp/phpDocumentor.phar /usr/local/bin/phpdoc creates=/usr/local/bin/phpdoc
  tags: [ 'common', 'phpdoc' ]

- name: Ensure phpDocumentor is executable
  file: path=/usr/local/bin/phpdoc mode=a+x state=file
  tags: [ 'common', 'phpdoc' ]