---
- name: List plugins
  shell: java -jar /opt/jenkins/jenkins-cli.jar -s http://localhost:8080 list-plugins | cut -f 1 -d ' '
  register: plugins_installed
  tags: [ 'jenkins-plugins' ]

- name: Install/update plugins
  shell: java -jar /opt/jenkins/jenkins-cli.jar -s http://localhost:8080 install-plugin {{ item }}
  when: plugins_installed.changed and plugins_installed.stdout.find('{{ item }}') == -1
  with_items:
      - cloverphp
      - git
      - git-client
      - scm-api
  notify: jenkins restart
  tags: [ 'jenkins-plugins' ]

- name: List plugins to be updated
  shell: java -jar /opt/jenkins/jenkins-cli.jar -s http://localhost:8080 list-plugins | grep ')$' | cut -f 1 -d ' ' | sed ':a;N;$!ba;s/\n/ /g'
  register: plugins_updates
  tags: [ 'jenkins-plugins' ]

- name: Update plugins
  shell: java -jar /opt/jenkins/jenkins-cli.jar -s http://localhost:8080 install-plugin {{ plugins_updates.stdout }}
  when: plugins_updates.stdout != ''
  notify: jenkins restart
  tags: [ 'jenkins-plugins' ]